# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia termica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [3]:
import pandas as pd

# Lista com as anomalias térmicas
anomalias = [-0.08, -0.27, 0.12, -0.03, 0.26, 0.40, 1.02]
anos = [1900, 1920, 1940, 1960, 1980, 2000, 2020]

#### 2) Coloque os anos nos índices conforme a tabela.

In [5]:
# Série com índice personalizado
serie_anomalias = pd.Series(anomalias, index=anos)
print("\nSérie com anos como índice:")
print(serie_anomalias)


Série com anos como índice:
1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
dtype: float64


#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [6]:
# Exemplo de dicionário
dados_dict = {
    "Brasil": 212.6,
    "Estados Unidos": 331.9,
    "Índia": 1380.0,
    "China": 1441.0,
    "Rússia": 146.0
}

serie_populacao = pd.Series(dados_dict)
print("\nSérie criada a partir de um dicionário:")
print(serie_populacao)


Série criada a partir de um dicionário:
Brasil             212.6
Estados Unidos     331.9
Índia             1380.0
China             1441.0
Rússia             146.0
dtype: float64


#### 4) Transforme o ndarray abaixo em um dataframe.
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [10]:
import numpy as np

# Criação de um array com distribuição normal (20 linhas e 3 colunas)
np.random.seed(1234)  # garante reprodutibilidade
array_dados = np.random.randn(20, 3)
print("\nArray criado:")
print(array_dados)

# Transformar em DataFrame
df = pd.DataFrame(array_dados)
print("\nDataFrame criado a partir do ndarray:")
print(df.head())


Array criado:
[[ 4.71435164e-01 -1.19097569e+00  1.43270697e+00]
 [-3.12651896e-01 -7.20588733e-01  8.87162940e-01]
 [ 8.59588414e-01 -6.36523504e-01  1.56963721e-02]
 [-2.24268495e+00  1.15003572e+00  9.91946022e-01]
 [ 9.53324128e-01 -2.02125482e+00 -3.34077366e-01]
 [ 2.11836468e-03  4.05453412e-01  2.89091941e-01]
 [ 1.32115819e+00 -1.54690555e+00 -2.02646325e-01]
 [-6.55969344e-01  1.93421376e-01  5.53438911e-01]
 [ 1.31815155e+00 -4.69305285e-01  6.75554085e-01]
 [-1.81702723e+00 -1.83108540e-01  1.05896919e+00]
 [-3.97840228e-01  3.37437654e-01  1.04757857e+00]
 [ 1.04593826e+00  8.63717292e-01 -1.22091575e-01]
 [ 1.24712954e-01 -3.22794806e-01  8.41674713e-01]
 [ 2.39096052e+00  7.61995878e-02 -5.66445930e-01]
 [ 3.61419367e-02 -2.07497760e+00  2.47792200e-01]
 [-8.97156784e-01 -1.36794833e-01  1.82891913e-02]
 [ 7.55413982e-01  2.15268581e-01  8.41008795e-01]
 [-1.44581008e+00 -1.40197328e+00 -1.00918200e-01]
 [-5.48242449e-01 -1.44619508e-01  3.54020332e-01]
 [-3.55130253e-0

#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [11]:
# Índices de 1 a 20
df.index = range(1, 21)

# Nome das colunas
df.columns = ["x1", "x2", "x3"]

print("\nDataFrame com índices e colunas nomeados:")
print(df.head())



DataFrame com índices e colunas nomeados:
         x1        x2        x3
1  0.471435 -1.190976  1.432707
2 -0.312652 -0.720589  0.887163
3  0.859588 -0.636524  0.015696
4 -2.242685  1.150036  0.991946
5  0.953324 -2.021255 -0.334077


#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [13]:
df["media"] = df[["x1", "x2", "x3"]].mean(axis=1)

print("\nDataFrame com a nova coluna 'media':")
print(df.head())


DataFrame com a nova coluna 'media':
         x1        x2        x3     media
1  0.471435 -1.190976  1.432707  0.237722
2 -0.312652 -0.720589  0.887163 -0.048693
3  0.859588 -0.636524  0.015696  0.079587
4 -2.242685  1.150036  0.991946 -0.033568
5  0.953324 -2.021255 -0.334077 -0.467336


#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>

In [15]:
df["log_med"] = np.log(df["media"])

print("\nDataFrame final com a coluna 'log_med':")
print(df.head())


DataFrame final com a coluna 'log_med':
         x1        x2        x3     media   log_med
1  0.471435 -1.190976  1.432707  0.237722 -1.436653
2 -0.312652 -0.720589  0.887163 -0.048693       NaN
3  0.859588 -0.636524  0.015696  0.079587 -2.530903
4 -2.242685  1.150036  0.991946 -0.033568       NaN
5  0.953324 -2.021255 -0.334077 -0.467336       NaN


/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
